/**
 * Configuração do Vitest para testes unitários da sprint S01-cnpj-alfanumerico.
 * Testa validadores, máscaras e BFF de CNPJ alfanumérico (IN RFB 2.229/2024).
 */
import { defineConfig } from "vitest/config";
import tsconfigPaths from "vite-tsconfig-paths";

export default defineConfig({
  plugins: [tsconfigPaths()],
  test: {
    environment: "jsdom",
    globals: true,
    setupFiles: ["./test/vitest.setup.ts"],
    // Exclui specs Playwright (sao executadas por `npm run test:e2e:playwright`).
    include: ["app/**/*.{test,spec}.{ts,tsx}", "test/unit/**/*.{test,spec}.{ts,tsx}"],
    exclude: [
      "node_modules/**",
      "build/**",
      "test/e2e/**",
      "**/*.e2e-spec.ts",
    ],
    pool: "forks",
    poolOptions: {
      forks: {
        singleFork: true,
      },
    },
    coverage: {
      provider: "v8",
      reporter: ["text", "html", "json-summary"],
      include: [
        "app/lib/cnpj-format.ts",
        "app/lib/cookies.ts",
        "app/lib/mask-utils.ts",
        "app/lib/new-startup-schema.ts",
        "app/lib/banking-schema.ts",
        "app/lib/currency-format.ts",
        "app/lib/fund-transfer-types.ts",
        "app/routes/api/geral.cnpj.$cnpj.ts",
        "app/routes/api/founder.startups.$id.repasse.ts",
        "app/components/founder/startup-actions-cell.tsx",
        "app/components/founder/startup-card.tsx",
        "app/components/founder/confirm-pause-round-dialog.tsx",
        "app/components/founder/confirm-cancel-round-dialog.tsx",
        "app/components/founder/fund-transfer-panel.tsx",
        "app/hooks/use-pause-round-mutation.ts",
        "app/hooks/use-cancel-round-mutation.ts",
        "app/hooks/use-fund-transfer-status.ts",
        "app/hooks/use-initiate-fund-transfer.ts",
        "app/lib/repasse-schemas.ts",
        "app/components/founder/repasse-dashboard.tsx",
        "app/components/founder/repasse-installment-form.tsx",
        "app/components/founder/repasse-allocation-input.tsx",
        "app/components/founder/repasse-educacional-tips.tsx",
        "app/components/founder/repasse-stepper.tsx",
        "app/components/founder/repasse-history.tsx",
        "app/components/foundation/repasse-sla-countdown.tsx",
        "app/components/compliance/repasse-deliberation-modal.tsx",
        "app/components/financeiro/repasse-config-modal.tsx",
        "app/components/financeiro/repasse-review-modal.tsx",
        "app/hooks/use-repasse-dashboard.ts",
        "app/hooks/use-create-solicitacao.ts",
        "app/hooks/use-resubmit-solicitacao.ts",
        "app/hooks/use-approve-installment.ts",
        "app/hooks/use-reject-installment.ts",
        "app/hooks/use-mark-installment-paid.ts",
        "app/hooks/use-compliance-deliberate.ts",
        "app/hooks/use-financeiro-configure-repasse.ts",
        "app/hooks/use-forgot-password-mutation.ts",
        "app/hooks/use-reset-password-mutation.ts",
        "app/hooks/use-validate-email-mutation.ts",
        "app/hooks/use-verify-2fa-mutation.ts",
        "app/hooks/use-cancel-payment-mutation.ts",
        "app/hooks/use-approve-payment-mutation.ts",
        "app/components/auth/forgot-password-form.tsx",
        "app/components/auth/reset-password-form.tsx",
        "app/components/auth/validate-email-form.tsx",
        "app/components/auth/two-factor-form.tsx",
        "app/components/checkout-payment/PixPayment.tsx",
        "app/components/checkout-payment/CreditCardRedirect.tsx",
        "app/components/financeiro/CancelModal.tsx",
        "app/components/financeiro/ApprovePaymentModal.tsx",
        "app/lib/queries.ts",
        "app/routes/api/founder.startups.$id.repasse.dashboard.ts",
        "app/routes/api/founder.startups.$id.repasse.installments.$installmentId.request.ts",
        "app/routes/api/founder.startups.$id.repasse.installments.$installmentId.resubmit.ts",
        "app/routes/api/financeiro.installments.$installmentId.approve.ts",
        "app/routes/api/financeiro.installments.$installmentId.reject.ts",
        "app/routes/api/financeiro.installments.$installmentId.mark-paid.ts",
        "app/routes/api/compliance.campaigns.$id.repasse.deliberate.ts",
        "app/routes/api/financeiro.repasses.$id.configure.ts",
      ],
      thresholds: {
        lines: 70,
        functions: 70,
        branches: 60,
        statements: 70,
      },
    },
  },
});
