// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  // Projeto 100% SQLite. O schema e as migrations MySQL foram descontinuados.
  schema: 'prisma/schema.sqlite.prisma',
  migrations: {
    path: 'prisma/migrations-sqlite',
    seed: 'ts-node prisma/seed.ts',
  },
  datasource: {
    url: process.env['DATABASE_URL'] ?? 'file:./prisma/dev.db',
  },
});
