// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/cadastro": {
    params: {};
  };
  "/payment/checkout/:token": {
    params: {
      "token": string;
    };
  };
  "/startup/:id": {
    params: {
      "id": string;
    };
  };
  "/auth/:token": {
    params: {
      "token": string;
    };
  };
  "/home": {
    params: {};
  };
  "/plans": {
    params: {};
  };
  "/perfil": {
    params: {};
  };
  "/startups/dashboard": {
    params: {};
  };
  "/startups/new": {
    params: {};
  };
  "/startups/campaigns": {
    params: {};
  };
  "/api/auth/login": {
    params: {};
  };
  "/api/auth/register": {
    params: {};
  };
  "/api/auth/logout": {
    params: {};
  };
  "/api/auth/token": {
    params: {};
  };
  "/api/auth/check-af2": {
    params: {};
  };
  "/api/auth/verify-af2": {
    params: {};
  };
  "/api/auth/new-token": {
    params: {};
  };
  "/api/auth/refresh": {
    params: {};
  };
  "/api/auth/new-code": {
    params: {};
  };
  "/api/user/me": {
    params: {};
  };
  "/api/user/update": {
    params: {};
  };
  "/api/user/upload-doc": {
    params: {};
  };
  "/api/document/upload": {
    params: {};
  };
  "/api/plans/findall": {
    params: {};
  };
  "/api/plans/subscription": {
    params: {};
  };
  "/api/startups/list-my": {
    params: {};
  };
  "/api/startups/post": {
    params: {};
  };
  "/api/startups/update": {
    params: {};
  };
  "/api/payment/transactions": {
    params: {};
  };
  "/api/payment/startup-checkout": {
    params: {};
  };
  "/api/payment/validate": {
    params: {};
  };
  "/api/payment/card": {
    params: {};
  };
  "/api/payment/pix": {
    params: {};
  };
  "/api/payment/pix/status": {
    params: {};
  };
  "/api/payment/cancel": {
    params: {};
  };
  "/api/geral/paises": {
    params: {};
  };
  "/api/geral/estados/:pais": {
    params: {
      "pais": string;
    };
  };
  "/api/geral/cidade/:pais/:estado": {
    params: {
      "pais": string;
      "estado": string;
    };
  };
  "/api/geral/cep/:cep": {
    params: {
      "cep": string;
    };
  };
  "/api/geral/cnpj/:cnpj": {
    params: {
      "cnpj": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/cadastro" | "/payment/checkout/:token" | "/startup/:id" | "/auth/:token" | "/home" | "/plans" | "/perfil" | "/startups/dashboard" | "/startups/new" | "/startups/campaigns" | "/api/auth/login" | "/api/auth/register" | "/api/auth/logout" | "/api/auth/token" | "/api/auth/check-af2" | "/api/auth/verify-af2" | "/api/auth/new-token" | "/api/auth/refresh" | "/api/auth/new-code" | "/api/user/me" | "/api/user/update" | "/api/user/upload-doc" | "/api/document/upload" | "/api/plans/findall" | "/api/plans/subscription" | "/api/startups/list-my" | "/api/startups/post" | "/api/startups/update" | "/api/payment/transactions" | "/api/payment/startup-checkout" | "/api/payment/validate" | "/api/payment/card" | "/api/payment/pix" | "/api/payment/pix/status" | "/api/payment/cancel" | "/api/geral/paises" | "/api/geral/estados/:pais" | "/api/geral/cidade/:pais/:estado" | "/api/geral/cep/:cep" | "/api/geral/cnpj/:cnpj";
  };
  "routes/page/index/index.tsx": {
    id: "routes/page/index/index";
    page: "/";
  };
  "routes/public/auth/login/index.tsx": {
    id: "routes/public/auth/login/index";
    page: "/login";
  };
  "routes/public/auth/cadastro/index.tsx": {
    id: "routes/public/auth/cadastro/index";
    page: "/cadastro";
  };
  "routes/public/payment/checkout/index.tsx": {
    id: "routes/public/payment/checkout/index";
    page: "/payment/checkout/:token";
  };
  "routes/page/startup/index.tsx": {
    id: "routes/page/startup/index";
    page: "/startup/:id";
  };
  "routes/public/auth/af2/index.tsx": {
    id: "routes/public/auth/af2/index";
    page: "/auth/:token";
  };
  "routes/layout/index.tsx": {
    id: "routes/layout/index";
    page: "/home" | "/plans" | "/perfil" | "/startups/dashboard" | "/startups/new" | "/startups/campaigns";
  };
  "routes/private/home/index.tsx": {
    id: "routes/private/home/index";
    page: "/home";
  };
  "routes/private/plans/index.tsx": {
    id: "routes/private/plans/index";
    page: "/plans";
  };
  "routes/private/perfil/index.tsx": {
    id: "routes/private/perfil/index";
    page: "/perfil";
  };
  "routes/private/startups/index.tsx": {
    id: "routes/private/startups/index";
    page: "/startups/dashboard";
  };
  "routes/private/startups/new/index.tsx": {
    id: "routes/private/startups/new/index";
    page: "/startups/new";
  };
  "routes/private/startups/campaigns/index.tsx": {
    id: "routes/private/startups/campaigns/index";
    page: "/startups/campaigns";
  };
  "routes/api/auth/login.ts": {
    id: "routes/api/auth/login";
    page: "/api/auth/login";
  };
  "routes/api/auth/register.ts": {
    id: "routes/api/auth/register";
    page: "/api/auth/register";
  };
  "routes/api/auth/logout.ts": {
    id: "routes/api/auth/logout";
    page: "/api/auth/logout";
  };
  "routes/api/auth/token.ts": {
    id: "routes/api/auth/token";
    page: "/api/auth/token";
  };
  "routes/api/auth/check-af2.ts": {
    id: "routes/api/auth/check-af2";
    page: "/api/auth/check-af2";
  };
  "routes/api/auth/verify-af2.ts": {
    id: "routes/api/auth/verify-af2";
    page: "/api/auth/verify-af2";
  };
  "routes/api/auth/new-token.ts": {
    id: "routes/api/auth/new-token";
    page: "/api/auth/new-token";
  };
  "routes/api/auth/refresh.ts": {
    id: "routes/api/auth/refresh";
    page: "/api/auth/refresh";
  };
  "routes/api/auth/new-code.ts": {
    id: "routes/api/auth/new-code";
    page: "/api/auth/new-code";
  };
  "routes/api/user/me.ts": {
    id: "routes/api/user/me";
    page: "/api/user/me";
  };
  "routes/api/user/update.ts": {
    id: "routes/api/user/update";
    page: "/api/user/update";
  };
  "routes/api/user/upload-doc.ts": {
    id: "routes/api/user/upload-doc";
    page: "/api/user/upload-doc";
  };
  "routes/api/document/upload.ts": {
    id: "routes/api/document/upload";
    page: "/api/document/upload";
  };
  "routes/api/plans/findall.ts": {
    id: "routes/api/plans/findall";
    page: "/api/plans/findall";
  };
  "routes/api/plans/subscription.ts": {
    id: "routes/api/plans/subscription";
    page: "/api/plans/subscription";
  };
  "routes/api/startups/list-my.ts": {
    id: "routes/api/startups/list-my";
    page: "/api/startups/list-my";
  };
  "routes/api/startups/post.ts": {
    id: "routes/api/startups/post";
    page: "/api/startups/post";
  };
  "routes/api/startups/update.ts": {
    id: "routes/api/startups/update";
    page: "/api/startups/update";
  };
  "routes/api/payment/transactions.ts": {
    id: "routes/api/payment/transactions";
    page: "/api/payment/transactions";
  };
  "routes/api/payment/startup-checkout.ts": {
    id: "routes/api/payment/startup-checkout";
    page: "/api/payment/startup-checkout";
  };
  "routes/api/payment/validate.ts": {
    id: "routes/api/payment/validate";
    page: "/api/payment/validate";
  };
  "routes/api/payment/card.ts": {
    id: "routes/api/payment/card";
    page: "/api/payment/card";
  };
  "routes/api/payment/pix.ts": {
    id: "routes/api/payment/pix";
    page: "/api/payment/pix";
  };
  "routes/api/payment/pix/status.ts": {
    id: "routes/api/payment/pix/status";
    page: "/api/payment/pix/status";
  };
  "routes/api/payment/cancel.ts": {
    id: "routes/api/payment/cancel";
    page: "/api/payment/cancel";
  };
  "routes/api/geral/paises.ts": {
    id: "routes/api/geral/paises";
    page: "/api/geral/paises";
  };
  "routes/api/geral/estados.ts": {
    id: "routes/api/geral/estados";
    page: "/api/geral/estados/:pais";
  };
  "routes/api/geral/cidade.ts": {
    id: "routes/api/geral/cidade";
    page: "/api/geral/cidade/:pais/:estado";
  };
  "routes/api/geral/cep.ts": {
    id: "routes/api/geral/cep";
    page: "/api/geral/cep/:cep";
  };
  "routes/api/geral/cnpj.ts": {
    id: "routes/api/geral/cnpj";
    page: "/api/geral/cnpj/:cnpj";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/page/index/index": typeof import("./app/routes/page/index/index.tsx");
  "routes/public/auth/login/index": typeof import("./app/routes/public/auth/login/index.tsx");
  "routes/public/auth/cadastro/index": typeof import("./app/routes/public/auth/cadastro/index.tsx");
  "routes/public/payment/checkout/index": typeof import("./app/routes/public/payment/checkout/index.tsx");
  "routes/page/startup/index": typeof import("./app/routes/page/startup/index.tsx");
  "routes/public/auth/af2/index": typeof import("./app/routes/public/auth/af2/index.tsx");
  "routes/layout/index": typeof import("./app/routes/layout/index.tsx");
  "routes/private/home/index": typeof import("./app/routes/private/home/index.tsx");
  "routes/private/plans/index": typeof import("./app/routes/private/plans/index.tsx");
  "routes/private/perfil/index": typeof import("./app/routes/private/perfil/index.tsx");
  "routes/private/startups/index": typeof import("./app/routes/private/startups/index.tsx");
  "routes/private/startups/new/index": typeof import("./app/routes/private/startups/new/index.tsx");
  "routes/private/startups/campaigns/index": typeof import("./app/routes/private/startups/campaigns/index.tsx");
  "routes/api/auth/login": typeof import("./app/routes/api/auth/login.ts");
  "routes/api/auth/register": typeof import("./app/routes/api/auth/register.ts");
  "routes/api/auth/logout": typeof import("./app/routes/api/auth/logout.ts");
  "routes/api/auth/token": typeof import("./app/routes/api/auth/token.ts");
  "routes/api/auth/check-af2": typeof import("./app/routes/api/auth/check-af2.ts");
  "routes/api/auth/verify-af2": typeof import("./app/routes/api/auth/verify-af2.ts");
  "routes/api/auth/new-token": typeof import("./app/routes/api/auth/new-token.ts");
  "routes/api/auth/refresh": typeof import("./app/routes/api/auth/refresh.ts");
  "routes/api/auth/new-code": typeof import("./app/routes/api/auth/new-code.ts");
  "routes/api/user/me": typeof import("./app/routes/api/user/me.ts");
  "routes/api/user/update": typeof import("./app/routes/api/user/update.ts");
  "routes/api/user/upload-doc": typeof import("./app/routes/api/user/upload-doc.ts");
  "routes/api/document/upload": typeof import("./app/routes/api/document/upload.ts");
  "routes/api/plans/findall": typeof import("./app/routes/api/plans/findall.ts");
  "routes/api/plans/subscription": typeof import("./app/routes/api/plans/subscription.ts");
  "routes/api/startups/list-my": typeof import("./app/routes/api/startups/list-my.ts");
  "routes/api/startups/post": typeof import("./app/routes/api/startups/post.ts");
  "routes/api/startups/update": typeof import("./app/routes/api/startups/update.ts");
  "routes/api/payment/transactions": typeof import("./app/routes/api/payment/transactions.ts");
  "routes/api/payment/startup-checkout": typeof import("./app/routes/api/payment/startup-checkout.ts");
  "routes/api/payment/validate": typeof import("./app/routes/api/payment/validate.ts");
  "routes/api/payment/card": typeof import("./app/routes/api/payment/card.ts");
  "routes/api/payment/pix": typeof import("./app/routes/api/payment/pix.ts");
  "routes/api/payment/pix/status": typeof import("./app/routes/api/payment/pix/status.ts");
  "routes/api/payment/cancel": typeof import("./app/routes/api/payment/cancel.ts");
  "routes/api/geral/paises": typeof import("./app/routes/api/geral/paises.ts");
  "routes/api/geral/estados": typeof import("./app/routes/api/geral/estados.ts");
  "routes/api/geral/cidade": typeof import("./app/routes/api/geral/cidade.ts");
  "routes/api/geral/cep": typeof import("./app/routes/api/geral/cep.ts");
  "routes/api/geral/cnpj": typeof import("./app/routes/api/geral/cnpj.ts");
};