import { Bell, Home, User } from "lucide-react";

export const afiliadoRoutes = [
  {
    id: 1,
    nome: 'Home',
    path: '/home',
    url: '/home',
    isActive: true,
    menu: 'geral',
    icon: Home,
  },
  {
    id: 2,
    nome: 'Dashboard',
    path: '/dashboard-afiliado',
    url: '/dashboard-afiliado',
    isActive: true,
    menu: 'geral',
    icon: null,
  },
  {
    id: 3,
    nome: 'Startup by id',
    path: '/startup/',
    url: '/startup/',
    isActive: true,
    menu: 'private',
    icon: null,
  },
  {
    id: 4,
    nome: 'Perfil',
    path: '/perfil',
    url: '/perfil',
    isActive: true,
    menu: 'user',
    icon: User,
  },
  {
    id: 5,
    nome: 'Notificação',
    path: '/notification',
    url: '/notification',
    isActive: true,
    menu: 'config',
    icon: Bell,
  },
  {
    id: 6,
    nome: 'Treinamento',
    path: '/treinamento',
    url: '/treinamento',
    isActive: true,
    menu: 'geral',
    icon: null,
  },
  {
    id: 7,
    nome: 'Painel financeiro',
    path: '/painel-financeiro',
    url: '/painel-financeiro',
    isActive: true,
    menu: 'geral',
    icon: null,
  },
  {
    id: 8,
    nome: 'Treinamento',
    path: '/treinamento',
    url: '/treinamento',
    isActive: true,
    menu: 'geral',
    icon: null,
  },
];
