import { Bell, Home, TrendingUp, User } from "lucide-react";

export const fundadorRoutes = [
  {
    id: 1,
    nome: 'Home',
    path: '/home',
    url: '/home',
    isActive: true,
    menu: 'geral',
    icon: Home,
  },
  {
    id: 2,
    nome: 'Dashboard',
    path: '/dashboard',
    url: '/dashboard',
    isActive: true,
    menu: 'geral',
    icon: null,
  },
  {
    id: 3,
    nome: 'Config Startup',
    path: '/config',
    url: '/config',
    isActive: true,
    menu: 'config',
    icon: null,
  },
  {
    id: 4,
    nome: 'Startup by id',
    path: '/startup/',
    url: '/startup',
    isActive: false,
    menu: 'private',
    icon: null,
  },
  {
    id: 5,
    nome: 'Perfil',
    path: '/perfil',
    url: '/perfil',
    isActive: true,
    menu: 'user',
    icon: User,
  },
  {
    id: 6,
    nome: 'Notificação',
    path: '/notification',
    url: '/notification',
    isActive: true,
    menu: 'config',
    icon: Bell,
  },
  {
    id: 7,
    nome: 'Treinamento',
    path: '/treinamento',
    url: '/treinamento',
    isActive: true,
    menu: 'geral',
    icon: null,
  },
  {
    id: 8,
    nome: 'Painel financeiro',
    path: '/painel-financeiro',
    url: '/painel-financeiro',
    isActive: true,
    menu: 'geral',
    icon: TrendingUp,
  },
  {
    id: 9,
    nome: 'Startup',
    path: '/dashboard_startups',
    url: '/dashboard_startups',
    isActive: true,
    menu: 'geral',
    icon: null,
  },
  {
    id: 10,
    nome: 'Checkout',
    path: '/checkout',
    url: '/checkout',
    isActive: false,
    menu: 'private',
    icon: null,
  },
  {
    id: 11,
    nome: 'Pagamento',
    path: '/payment',
    url: '/payment',
    isActive: false,
    menu: 'private',
    icon: null,
  },
  {
    id: 12,
    nome: 'Startups by id',
    path: '/privat/startup/',
    url: '/privat/startup',
    isActive: false,
    menu: 'private',
    icon: null,
  }
];
