import { Rotas } from "@/types/rotasTypes";
import { Bell, ChartNoAxesCombined, Home, NotebookPen, User } from "lucide-react";

export const userRoutes: Rotas.Types[] = [
  {
    id: 1,
    nome: 'Home',
    path: '/home',
    url: '/home',
    isActive: true,
    menu: 'geral',
    icon: Home,
  },
  {
    id: 2,
    nome: 'Perfil',
    path: '/perfil',
    isActive: true,
    url: '/perfil',
    menu: 'user',
    icon: User,
  },
  {
    id: 3,
    nome: 'Notificação',
    path: '/notification',
    url: '/notification',
    isActive: true,
    menu: 'config',
    icon: Bell,
  },
  {
    id: 4,
    nome: 'Startup by id',
    path: '/startup/',
    url: '/startup/',
    isActive: true,
    menu: 'private',
    icon: null,
  },
  {
    id: 5,
    nome: 'Painel Financeiro',
    path: '/painel-financeiro',
    url: '/painel-financeiro',
    isActive: true,
    menu: 'geral',
    icon: ChartNoAxesCombined,
  },
  {
    id: 6,
    nome: 'Treinamento',
    path: '/treinamento',
    url: '/treinamento',
    isActive: true,
    menu: 'interno',
    icon: NotebookPen,
  },
  {
    id: 7,
    nome: 'Detalhes da Startup',
    path: '/privat/startup/',
    url: '/privat/startup',
    isActive: false,
    menu: 'private',
    icon: null,
  },
  {
    id: 8,
    nome: 'Business',
    path: '/business',
    url: '/business',
    isActive: false,
    menu: 'private',
    icon: null,
  },
  {
    id: 9,
    nome: 'Planos',
    path: '/business/plans',
    url: '/business/plans',
    isActive: true,
    menu: 'user',
    icon: NotebookPen,
  },
];